# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a381df3e5fe35af1074f0b30c779d5e48e83a49d58495fff1a223bdf3a4ec706425a25224728ae6076172868f928d4bd81e2a11bb943d921af2293bb5491edbc

test:
  secret_key_base: 983b95ce70f6196b171b5bf34f43f5d4149e00691983e72f08fe6f1aec424f21e16d1047ab57d4676c1a2c1cee5edd8b05c8b11a98a8b3323805d04cb272a19c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
